### ISSUE TITLE
My favourite music application

### ISSUE THREAD

**Issue by WillemPaternotte** [lonkaars/musicopy#1]
Hello,

I just found your project and i find it really intressting,
But I couldn't help my self to not ask: Will this project be compatible in any way or form with my favourite music application called fitopsy?(https://github.com/WillemPaternotte/fitopsy)
I'd love to be able to use this together with fitopsy(my fauvorite music application).
Well, I hope you can implement this, because i really love the intuitive design that fitopsy gives it's users. So being able to use this together with the amazing application fitopsy would be great!

sincerely, me :)

**Comment by lonkaars** [comment]
haha python poopy language haha stinky uh oh

**Comment by WillemPaternotte** [comment]
:( je sterretje is weg.
